# Training hyperparameter

# optimizer hyperparameter
optim: AdamW
weight_decay: 0.0005
momentum: 0.937
max_lr: 2e-4
min_lr: 2e-7
lr_scheduler: OneCycleLR # [ReduceLROnPlateau, CosineAnnealingLR, OneCycleLR]
pursuit_metric : ap # [precision, recall, f1_score, accuracy, ap, precision_k], metric to be persuit during training. early stopping and best model will follow this metrics value.
better : max #  [max, min], mode to account values of the chosen metric.
# data augmentation hyperparameter
Resize: [224, 1] # [image size for training, interpolation mode], 1(Default):cv2.INTER_LINEAR (BILINEAR), 2:cv.INTER_CUBIC (BICUBIC).
Normalize : [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225], 1] # [mean, std, probability]
RandomHorizontalFlip: 0.5  # horizontal flip (probability) range 0-1.
RandomAffine: [0.02, [0.95, 0.99], [-15,15] ,0] # [translate_percent=(float), scale=(float,float), rotate=(float,float) probability]
ColorJitter: [0.05, 0.05, 0.05, 0.1, 0] # [brightness, contrast, saturation, hue, probability]
RandomPerspective: [[0.1,0.2], 0] # [distortion_scale, probability]
GaussianBlur : [[3, 5], [0.1, 1.1], 0] # [blur_limit, sigma_limit=(float, float), probability]
RandomAdjustSharpness: [[0.1, 0.3], [0.7, 1.0], 0] # [alpha, lightness ,probability]
